<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB; // Import the DB facade

class ReportController extends Controller
{
    public function productPerformance()
    {
        $products = Product::query()
            // Select the basic product info
            ->select('products.id', 'products.name', 'products.price')
            // Calculate the total units sold by summing the quantity from the pivot table
            ->addSelect(DB::raw('SUM(order_product.quantity) as total_sold'))
            // Calculate the total revenue generated by this product
            ->addSelect(DB::raw('SUM(order_product.quantity * order_product.price) as total_revenue'))
            // Join with the pivot table to access sales data
            ->join('order_product', 'products.id', '=', 'order_product.product_id')
            // Group the results by product to get correct sums
            ->groupBy('products.id', 'products.name', 'products.price')
            // Order by the best-selling products first
            ->orderBy('total_sold', 'desc')
            ->get();

        return view('admin.reports.product_performance', compact('products'));
    }
}